<body id="addVideo">
    <section id="videos">
        <form method="POST" class="form formChalet">
            <h3>l'ajout d'une vidéo </h3>
            <div class="inputBox">
                <input type="text" name="url_video" placeholder="lien de la video">       
            </div>
            <div class="inputBox">
                <button type="submit" name="submit">Ajouter</button>
            </div>    
        </form>
    </section>
</body>


