<table id="displayChalet">
                
    <?php foreach($result as $Service) :?>
        <tr>
            <td class="description"><a href="detailChalet.php?id=<?=$Service['id_chalet'] ?>"><h3><?= $Service["name"] ?></h3></a>
            <p><?=$Service['description'] ?><p>
            <p class="detailChalet"><?=$Service['massif'] ?> / <?=$Service['station'] ?><br>
            <?=$Service['price'] ?> € </p></td>
            <td><a href="detailChalet.php?id=<?=$Service['id_chalet'] ?>"><img src="img/slider/<?=$Service["chalet"] ?>" class="imgChalet" alt="<?= $Service["name"] ?>"></a>
            <td>
        </tr>    
    <?php endforeach; ?>

</table>

