
<table id=displayChalet>
                    
    <?php
        $req=$pdo->query('SELECT * FROM chalet LIMIT ' .$depart. ',' .$nombre_articles_par_page);
        while($chalet = $req->fetch()) {
    ?>

    <tr>
        <td class="description"><a href="detailChalet.php?id=<?=$chalet['id_chalet'] ?>"><h3><?= $chalet["name"] ?></h3></a>
            <p><?=$chalet['description'] ?><p>
            <p class="detailChalet"><?=$chalet['massif'] ?> / <?=$chalet['station'] ?><br>
            <?=$chalet['price'] ?> € </p>
        </td>                    
        <td>
            <section class="chaletPromo">
                <img src="img/slider/<?=$chalet["chalet"] ?>" class="imgPromo" alt="<?= $chalet["name"] ?>">        
                <div class="masque_Admin"></div>   
                <div>    
                    <button class="buttonEdit"><a href="editChalet.php?id=<?= $chalet['id_chalet'] ?>">Mettre à jour</a></button>
                </div>
                <div>    
                    <button class="buttonCancel"><a href="deletChalet.php?id=<?= $chalet['id_chalet'] ?>">Suprimer</a></button>
                </div>
            </section>                                                                
        </td>                                    
    </tr>

    <?php 
        }
    ?>
    
</table>

<?php 
    echo '<div id="pagination">' . $pagination . '</div>';
?>