
<section>
    <?php if($showcookie) { ?>
        <div class="cookie-alert">
            <p>En poursuivant votre navigation sur ce site, vous acceptez l’utilisation de cookies pour vous proposer des contenus et services adaptés à vos centres d’intérêts.</p>
            <a href="./accept_cookie.php">OK</a>
        </div>
    <?php } ?>
</section>

<section id="bandeau-footer">
    <section class="logo-footer">
        <a href="index.php" class="logo"><img src="img/img_logos/logoChalet-03.png" alt="logo du site">
        <p class='textLogo'>Chalet Vacances </p></a>
    </section>
    <section class="social-networks">
        <h3>suivez-nous</h3>
        <ul>
            <li>
                <i class="fab fa-twitter-square"></i>
            </li>
            <li>
                <i class="fab fa-facebook-square"></i>
            </li>
            <li>
                <i class="fab fa-youtube-square"></i>
            </li>
            <li>
                <i class="fab fa-linkedin"></i>
            </li>
        </ul>
    </section>
</section>  

<section class="container-footer">
    <section id="footerService">
        <ul>
            <li><a href="chaletAlpesDuNord.php">Chalet Alpes du Nord</a></li>
            <li><a href="ChaletAlpesDuSud.php">Chalet Alpes du Sud</a></li>
            <li><a href="ChaletVosges.php">Chalet Vosges</a></li>
            <li><a href="ChaletValais.php">Chalet Valais</a></li>
        </ul>
    </section>
    <section id="partenaire">
        <img src="img/img_logos/logo-partenaire2.jpg" alt="logo partenaire">
        <img src="img/img_logos/logo-partenaire5.jpg" alt="logo partenaire">
        <img src="img/img_logos/logo-partenaire6.jpg" alt="logo partenaire" >
        <img src="img/img_logos/logo-partenaire7.png" alt="logo partenaire">
    </section>
    <section id="info-contact">
        <h3>Nous Contacter</h3>
        <p><i class="fas fa-mobile-alt icon"></i><span>33 (0) 3 92 35 17 78</span></p>
        <p><i class="fas fa-at"></i><span>chalet.vacances@gmail.com</span></p>
        <p><i class="fas fa-address-card"></i><span>195 rue Victor Hugo - 73150 Val-d'Isère - Savoie - FRANCE </span></p>
    </section>
</section>



